services:
  - type: web
    name: minimatch-fast
    runtime: static
    rootDir: landing
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /
        name: Cache-Control
        value: public, max-age=3600
      - path: /index.html
        name: Cache-Control
        value: public, max-age=3600
